#! /bin/sh
set -e

# The following only on a new install
if [ "$1" = "configure" ]; then

  update-firefox
  # The following only on a new install
  if [ "$2" = "" ]; then
    echo "Instalando Firefox por primera vez"
    if [ -f /opt/firefox/firefox ]; then
      update-alternatives --install /usr/bin/x-www-browser x-www-browser /opt/firefox/firefox 10
      update-alternatives --install /usr/bin/gnome-www-browser gnome-www-browser /opt/firefox/firefox 10
    fi
  fi

fi

exit 0
#DEBHELPER#
