#! /bin/sh
set -e

# The following only on a new install
if [ "$1" = "configure" ]; then

  update-firefox
  # The following only on a new install
  if [ "$2" = "" ]; then
    echo "Instalando Firefox por primera vez"
  fi

fi

exit 0
#DEBHELPER#
